### ISSUE TITLE
yaml loader warning

### ISSUE THREAD

**Issue by madivad** [zacscott/pyasx#6]
when retrieving a list of listed companies (and possibly other times) a warning is displayed

    >>> res = pyasx.data.companies.get_listed_companies()
    /home/dave/.local/lib/python3.6/site-packages/pyasx/config.py:30: 
    YAMLLoadWarning: calling yaml.load() without Loader=... 
    is deprecated, as the default Loader is unsafe. 
    Please read https://msg.pyyaml.org/load for full details.
      _config = yaml.load(yaml_stream)

as per:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation#how-to-disable-the-warning

I have just created my first ever pull request to fix this, but I urge you to check it out (it seemed so easy that even I couldn't stuff it up! lol)

**Comment by zacscott** [comment]
Hi mate,

I believe that issue is with PyYaml 5.1 only, The version specified in requirements.txt was working without any warnings when I tested just now.

I've still merged your PR and upgraded PyYaml to 5.1 latest, probs best to do that anyway. Have released a new version 2.2 along with a few other bug fixes I noticed while testing.
